SELECT es.MATRICULA
FROM EMPREGADO e, EMPREGADO es, VENDA v, ITENS_VENDA iv, PRODUTO p, CATEGORIA c
WHERE EXTRACT(MONTH FROM V.DT_VENDA) = 05 AND
      c.NOME = 'Higiene' AND
      c.ID_CATEGORIA = p.ID_CATEGORIA AND
      p.ID_PROD = iv.ID_PROD AND
      iv.ID_VENDA = v.ID_VENDA AND
      v.MATRICULA = e.MATRICULA AND
      e.SUPERVISOR = es.MATRICULA
