CREATE VIEW VIEW_CATEGORIA_VENDIDAS AS
    SELECT  C.NOME as "Categoria", 
            NVL(SUM(VENDIDO.PRECO_UNITARIO * VENDIDO.QUANTIDADE), 0) AS "Total Vendido"
    FROM CATEGORIA C
    INNER JOIN PRODUTO P ON C.ID_CATEGORIA = P.ID_CATEGORIA
    INNER JOIN ITENS_VENDA VENDIDO ON P.ID_PROD = VENDIDO.ID_PROD
    WHERE   (P.DT_VALIDADE <= '12-JUL-2018')
    GROUP BY C.NOME
    order by (SUM(VENDIDO.PRECO_UNITARIO * VENDIDO.QUANTIDADE)) DESC