SELECT  PROD.NOME AS "Produto"
FROM PRODUTO PROD
INNER JOIN ITENS_VENDA ITEM ON PROD.ID_PROD = ITEM.ID_PROD
INNER JOIN VENDA VENDA ON ITEM.ID_VENDA = VENDA.ID_VENDA
WHERE   (EXTRACT(YEAR FROM VENDA.DT_VENDA) != 2015 AND 
        EXTRACT(YEAR FROM VENDA.DT_VENDA) != 2016)
GROUP BY PROD.NOME