SELECT  PROD.NOME AS "Produto",
        PROD.QUANT as "Quant"
FROM PRODUTO PROD
INNER JOIN ITEM_VENDA ITEM ON PROD.ID_PRODUTO = ITEM.ID_PRODUTO
INNER JOIN VENDA VENDA ON ITEM.ID_VENDA = VENDA.ID_VENDA
WHERE   (EXTRACT(YEAR FROM VENDA.DT_VENDA) != 2015 AND 
        EXTRACT(YEAR FROM VENDA.DT_VENDA) != 2016)
GROUP BY PROD.NOME