SELECT  CLI.ID_CLIENTE AS "ID_CLIENTE",
        NVL(SUM(ITEM.PRECO_UNITARIO * ITEM.QUANTIDADE), 0) as "TOTAL_GASTO"
FROM CLIENTE CLI
INNER JOIN VENDA VENDA ON CLI.ID_CLIENTE = VENDA.ID_CLIENTE
INNER JOIN ITENS_VENDA ITEM ON VENDA.ID_VENDA = ITEM.ID_VENDA
INNER JOIN PRODUTO PROD ON ITEM.ID_PROD = PROD.ID_PROD
INNER JOIN CATEGORIA CAT ON PROD.ID_CATEGORIA = CAT.ID_CATEGORIA
WHERE (CLI.END_BAIRRO = 'Prata' and CAT.NOME = 'Utensílios')
GROUP BY CLI.ID_CLIENTE