CREATE OR REPLACE TRIGGER "DATA_ENTREGA"
AFTER
UPDATE OF "DT_ENTREGA" ON "VENDA"
FOR EACH ROW
WHEN ((NEW.DT_ENTREGA - OLD.DT_VENDA) > 30)
BEGIN
UPDATE CLIENTE
SET CLIENTE.BONUS = CLIENTE.BONUS + :NEW.FRETE
WHERE CLIENTE.ID_CLIENTE = :NEW.ID_CLIENTE;
END;
