DROP TABLE CLIENTE CASCADE CONSTRAINTS;
CREATE TABLE CLIENTE(
ID_CLIENTE INT,
CPF CHAR(11),
NOME CHAR(15),
SOBRENOME VARCHAR(40),
TITULO_TRATAMENTO CHAR (3),
DT_NASCIMENTO DATE,
SEXO CHAR(1),
END_RUA CHAR(30),

END_NUM CHAR(5),
END_CIDADE CHAR(20),
END_BAIRRO CHAR(15),
END_ESTADO CHAR(2),
END_PAIS CHAR(20),
END_CEP CHAR(7),
TELEFONE CHAR(11),
EMAIL CHAR(50),
BONUS NUMERIC (6,2),
PRIMARY KEY (ID_CLIENTE),
CONSTRAINT CHK_BONUS_CLIENTE CHECK (BONUS >= 0)
);
DROP TABLE DEPENDENTE CASCADE CONSTRAINTS;
CREATE TABLE DEPENDENTE(
ID_DEP INT,
ID_CLIENTE INT,
NOME CHAR(50),
SEXO CHAR (2),
DT_NASC DATE,
PRIMARY KEY (ID_DEP, ID_CLIENTE),
FOREIGN KEY (ID_CLIENTE) REFERENCES
CLIENTE(ID_CLIENTE) ON DELETE CASCADE
);

DROP TABLE EMPREGADO CASCADE CONSTRAINTS;

CREATE TABLE EMPREGADO (
MATRICULA INT,

NOME CHAR(50),
FUNCAO CHAR(15),
DT_NASCIMENTO DATE,
DT_CONTRATO DATE,
ENDEREÇO CHAR(100),
SALARIO NUMERIC (7,2),
SUPERVISOR INT,
PRIMARY KEY (MATRICULA),
FOREIGN KEY (SUPERVISOR) REFERENCES EMPREGADO
(MATRICULA) ON DELETE SET NULL
);

DROP TABLE TELEFONES_EMP CASCADE CONSTRAINTS;

CREATE TABLE TELEFONES_EMP (
MATRICULA INT,
NUMERO CHAR(15),
PRIMARY KEY (MATRICULA, NUMERO)
);

DROP TABLE REGIAO CASCADE CONSTRAINTS;

CREATE TABLE REGIAO (
ID_REGIAO INT,
NOME VARCHAR(15),
PRIMARY KEY (ID_REGIAO)
);

DROP TABLE EMP_ATUA_REGIAO CASCADE CONSTRAINTS;

CREATE TABLE EMP_ATUA_REGIAO (
MATRICULA INT,
ID_REGIAO INT,
PRIMARY KEY (MATRICULA, ID_REGIAO),
FOREIGN KEY (MATRICULA) REFERENCES
EMPREGADO(MATRICULA),
FOREIGN KEY(ID_REGIAO) REFERENCES REGIAO (ID_REGIAO)
);

DROP TABLE TRANSPORTADORA CASCADE CONSTRAINTS;

CREATE TABLE TRANSPORTADORA (
ID_TRANSP INT,
NOME VARCHAR(30),
EMAIL VARCHAR(30),
PRIMARY KEY (ID_TRANSP)
);

DROP TABLE TELEFONES_TRANSP CASCADE CONSTRAINTS;

CREATE TABLE TELEFONES_TRANSP (
ID_TRANSP INT,
NUMERO CHAR(11),
PRIMARY KEY(ID_TRANSP, NUMERO)
);

DROP TABLE FORNECEDOR CASCADE CONSTRAINTS;

CREATE TABLE FORNECEDOR (
ID_FORN INT,
NOME VARCHAR(30),
EMAIL VARCHAR(30),
ENDERECO CHAR(50),
TELEFONE CHAR(11),
HOMEPAGE CHAR(30),
PRIMARY KEY(ID_FORN)
);

DROP TABLE CATEGORIA CASCADE CONSTRAINTS;

CREATE TABLE CATEGORIA (
ID_CATEGORIA INT,
NOME VARCHAR(20),
PRIMARY KEY(ID_CATEGORIA)
);

DROP TABLE PRODUTO CASCADE CONSTRAINTS;

CREATE TABLE PRODUTO (
ID_PROD INT,
NOME CHAR(30),
PRECO_COMPRA NUMERIC (7,2),
MARGEM_LUCRO FLOAT,

DESCONTINUADO CHAR(1),
DT_FABRIC DATE,
DT_VALIDADE DATE,
ID_FORN INT,
ID_CATEGORIA INT,
PRIMARY KEY (ID_PROD),
FOREIGN KEY (ID_FORN) REFERENCES FORNECEDOR
(ID_FORN),
FOREIGN KEY (ID_CATEGORIA) REFERENCES CATEGORIA
(ID_CATEGORIA)
);

DROP TABLE VENDA CASCADE CONSTRAINTS;

CREATE TABLE VENDA (
ID_VENDA INT,
DT_VENDA DATE NOT NULL,
FRETE NUMERIC (4,2),
ENDERECO_ENTREGA VARCHAR(100),
DT_ENTREGA DATE,
ID_TRANSP INT,
ID_CLIENTE INT NOT NULL,
MATRICULA INT,
PRIMARY KEY(ID_VENDA),
FOREIGN KEY (ID_TRANSP) REFERENCES TRANSPORTADORA
(ID_TRANSP),
FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE
(ID_CLIENTE),
FOREIGN KEY (MATRICULA) REFERENCES EMPREGADO
(MATRICULA)

);

DROP TABLE ITENS_VENDA CASCADE CONSTRAINTS;

CREATE TABLE ITENS_VENDA (
ID_ITEM INT,
PRECO_UNITARIO NUMBER (7,2) NOT NULL,
QUANTIDADE INT NOT NULL,
DESCONTO FLOAT,
ID_VENDA INT,
ID_PROD INT,
PRIMARY KEY (ID_ITEM),
FOREIGN KEY (ID_VENDA) REFERENCES VENDA (ID_VENDA),
FOREIGN KEY (ID_PROD) REFERENCES PRODUTO (ID_PROD)
);