CREATE TABLE CLIENTE (
    CPF CHAR(11),
    ID_CLIENTE INTEGER PRIMARY KEY,
    NOME VARCHAR(255),
    SOBRENOME VARCHAR(255),
    DT_NASCIMENTO DATE,
    SEXO CHAR(1),
    TELEFONE VARCHAR(255),
    EMAIL VARCHAR(255),
    RUA VARCHAR(255),
    NUM VARCHAR(255),
    BAIRRO VARCHAR(255),
    CIDADE VARCHAR(255),
    ESTADO VARCHAR(255),
    PAIS VARCHAR(255),
    CEP CHAR(8),
    CONSTRAINT check_sexo_cliente CHECK (SEXO = 'M' OR SEXO = 'F')
);

CREATE TABLE DEPENDENTE (
    ID_DEP INTEGER PRIMARY KEY,
    NOME VARCHAR(255),
    SEXO CHAR(1),
    DT_NASC DATE,
    FK_CLIENTE_ID_CLIENTE INTEGER,
    CONSTRAINT check_sexo_dependente CHECK (SEXO = 'M' OR SEXO = 'F')
);

CREATE TABLE TRANSPORTADORA (
    ID_TRANSP INTEGER PRIMARY KEY,
    NOME VARCHAR(255),
    TELEFONES VARCHAR(255),
    EMAIL VARCHAR(255)
);

CREATE TABLE VENDA (
    ID_VENDA INTEGER PRIMARY KEY,
    FRETE NUMBER(*,2),
    ENDERECO VARCHAR(255),
    FK_TRANSPORTADORA_ID_TRANSP INTEGER,
    DT_ENTREGA DATE,
    FK_EMPREGADO_MATRICULA INTEGER,
    FK_CLIENTE_ID_CLIENTE INTEGER,
    CONSTRAINT check_preco_frete CHECK(FRETE > 0)
);

CREATE TABLE EMPREGADO (
    MATRICULA INTEGER PRIMARY KEY,
    NOME VARCHAR(255),
    FUNCAO VARCHAR(255),
    DT_NASCIMENTO DATE,
    DT_CONTRATO DATE,
    ENDERECO VARCHAR(255),
    TELEFONES VARCHAR(255),
    SALARIO NUMBER(*,2),
    FK_REGIAO_ID_REGIAO INTEGER,
    CONSTRAINT check_salario CHECK(SALARIO > 0)
);

CREATE TABLE PRODUTO (
    ID_PROD NUMBER PRIMARY KEY,
    NOME VARCHAR(255),
    PRECO_COMPRA NUMBER(*,2),
    MARGEM_LUCRO NUMBER,
    DESCONTINUADO CHAR(1),
    DT_FABRIC DATE,
    DT_VALIDADE DATE,
    FK_FORNECEDOR_ID_FORN INTEGER,
    FK_CATEGORIA_ID_CATEGORIA INTEGER,
    CONSTRAINT check_descontinuado CHECK (DESCONTINUADO = 1 OR DESCONTINUADO = 0),
    CONSTRAINT check_preco_compra CHECK (PRECO_COMPRA > 0)
);

CREATE TABLE FORNECEDOR (
    ID_FORN INTEGER PRIMARY KEY,
    NOME VARCHAR(255),
    EMAIL VARCHAR(255),
    ENDERECO VARCHAR(255),
    TELEFONE VARCHAR(255),
    HOMEPAGE VARCHAR(255)
);

CREATE TABLE CATEGORIA (
    ID_CATEGORIA INTEGER PRIMARY KEY,
    NOME VARCHAR(255)
);

CREATE TABLE REGIAO (
    ID_REGIAO INTEGER PRIMARY KEY,
    NOME VARCHAR(255),
    FK_EMPREGADO_MATRICULA INTEGER
);

CREATE TABLE SUPERVISIONA (
    FK_EMPREGADO_MATRICULA INTEGER,
    FK_EMPREGADO_MATRICULA_ INTEGER
);

CREATE TABLE VENDA_PRODUTO (
    FK_PRODUTO_ID_PROD NUMBER,
    FK_VENDA_ID_VENDA INTEGER,
    PRECO_UNITARIO NUMBER(*,2),
    QUANTIDADE NUMBER,
    DESCONTO NUMBER(*,2),
    /*CONSTRAINT check_preco_venda CHECK (PRECO_UNITARIO >= PRODUTO.PRECO_COMPRA),*/
    CONSTRAINT check_quantidade CHECK (QUANTIDADE > 1)
);
 
ALTER TABLE DEPENDENTE ADD CONSTRAINT FK_DEPENDENTE_1
    FOREIGN KEY (FK_CLIENTE_ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);
 
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_1
    FOREIGN KEY (FK_TRANSPORTADORA_ID_TRANSP)
    REFERENCES TRANSPORTADORA (ID_TRANSP);
 
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_2
    FOREIGN KEY (FK_EMPREGADO_MATRICULA)
    REFERENCES EMPREGADO (MATRICULA);
 
ALTER TABLE VENDA ADD CONSTRAINT FK_VENDA_3
    FOREIGN KEY (FK_CLIENTE_ID_CLIENTE)
    REFERENCES CLIENTE (ID_CLIENTE);
 
ALTER TABLE EMPREGADO ADD CONSTRAINT FK_EMPREGADO_1
    FOREIGN KEY (FK_REGIAO_ID_REGIAO)
    REFERENCES REGIAO (ID_REGIAO);
 
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_1
    FOREIGN KEY (FK_FORNECEDOR_ID_FORN)
    REFERENCES FORNECEDOR (ID_FORN);
 
ALTER TABLE PRODUTO ADD CONSTRAINT FK_PRODUTO_2
    FOREIGN KEY (FK_CATEGORIA_ID_CATEGORIA)
    REFERENCES CATEGORIA (ID_CATEGORIA);
 
ALTER TABLE REGIAO ADD CONSTRAINT FK_REGIAO_1
    FOREIGN KEY (FK_EMPREGADO_MATRICULA)
    REFERENCES EMPREGADO (MATRICULA);
 
ALTER TABLE SUPERVISIONA ADD CONSTRAINT FK_SUPERVISIONA_0
    FOREIGN KEY (FK_EMPREGADO_MATRICULA)
    REFERENCES EMPREGADO (MATRICULA);
 
ALTER TABLE SUPERVISIONA ADD CONSTRAINT FK_SUPERVISIONA_1
    FOREIGN KEY (FK_EMPREGADO_MATRICULA_)
    REFERENCES EMPREGADO (MATRICULA);
 
ALTER TABLE VENDA_PRODUTO ADD CONSTRAINT FK_VENDA_PRODUTO_0
    FOREIGN KEY (FK_PRODUTO_ID_PROD)
    REFERENCES PRODUTO (ID_PROD);
 
ALTER TABLE VENDA_PRODUTO ADD CONSTRAINT FK_VENDA_PRODUTO_1
    FOREIGN KEY (FK_VENDA_ID_VENDA)
    REFERENCES VENDA (ID_VENDA);